Fail fast on bad msa or hmm programs

diff --git a/test/slow/flaky_msa_program.t/flaky_mafft b/test/slow/flaky_msa_program.t/flaky_mafft
--- a/test/slow/flaky_msa_program.t/flaky_mafft
+++ b/test/slow/flaky_msa_program.t/flaky_mafft
@@ -9,14 +9,16 @@
 # $ RUN_FLAKY_MAFFT=apple_pie ./flaky_mafft 
 # mafft failed :(
 
-
-if [ -f $RUN_FLAKY_MAFFT ]; then
-    rm $RUN_FLAKY_MAFFT
-    mafft "$@"
-    # printf "mafft succeeded :)\n"
+if [ "${1}" = "--version" ]; then
+    exit 0
 else
-    touch $RUN_FLAKY_MAFFT
-    printf "mafft failed :(\n" 2>&1
-    exit 1
+    if [ -f $RUN_FLAKY_MAFFT ]; then
+	rm $RUN_FLAKY_MAFFT
+	mafft "$@"
+	# printf "mafft succeeded :)\n"
+    else
+	touch $RUN_FLAKY_MAFFT
+	printf "mafft failed :(\n" 2>&1
+	exit 1
+    fi
 fi
-
